server:
  port: 8081
spring:
  application:
    name: boardbox_catalog
  r2dbc:
    url: r2dbc:postgresql://db:5433/boardbox
    username: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://db:5433/boardbox
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/catalog-master.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
